### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by brianteeman**
simple copy paste error in the comments

### CODE REVIEW

**Comment by maboa** [comment]
Thanks!

**Comment by brianteeman** [comment]
my pleasure

**Comment by maboa** [comment]
@brianteeman Hi there - just going through and reviewing previous PRs and I noticed that I had forgotten to ask you to sign our CLA - would it be possible for you to do that now? - Thanks so much in advance https://hyperaud.io/cla/

**Comment by brianteeman** [comment]
and done

**Pull request merged**
